### PR TITLE
Sprint 1 Final Pull

### PR DESCRIPTION
**Pull request by ianreger**
- Save and Load tests created
- Installers for each OS added
- ReadMe and Usage added
- General clean up (spaces and such) for consistency and comments.

### CODE REVIEW

**Review by cjnissle — APPROVED** [review]
Looks good.

**Review by amstone2 — APPROVED** [review]
All looks good.

**Comment by bubbles96** [comment]
Everything looks correct and completed for this sprint

**Review by nybblybit — COMMENTED** [review]
Sprint 1 is complete and looks good

**Review by nybblybit — APPROVED** [review]

**Pull request merged**
